var fractalNames = {
    "en": {
        1: "Urban Battleground",
        2: "Swampland (Bloomhunger)",
        3: "Aquatic Ruins (Dark Path)",
        4: "Uncategorized",
        5: "Snowblind",
        6: "Volcanic",
        7: "Cliffside",
        8: "Underground Facility (Guns)",
        9: "Molten Furnace",
        10: "Molten Boss",
        11: "Urban Battleground",
        12: "Uncategorized",
        13: "Cliffside",
        14: "Aetherblade",
        15: "Thaumanova Reactor",
        16: "Snowblind",
        17: "Underground Facility (Bombs)",
        18: "Aquatic Ruins (Dolphin Path)",
        19: "Volcanic",
        20: "Solid Ocean",
        21: "Swampland (Mossman)",
        22: "Cliffside",
        23: "Molten Furnace",
        24: "Aetherblade",
        25: "Captain Mai Trin Boss",
        26: "Aquatic Ruins (Dolphin Path)",
        27: "Snowblind",
        28: "Volcanic",
        29: "Underground Facility (Bombs)",
        30: "Solid Ocean",
        31: "Urban Battleground",
        32: "Swampland (Bloomhunger)",
        33: "Cliffside",
        34: "Thaumanova Reactor",
        35: "Solid Ocean",
        36: "Uncategorized",
        37: "Snowblind",
        38: "Underground Facility (Guns)",
        39: "Molten Furnace",
        40: "Molten Boss",
        41: "Swampland (Mossman)",
        42: "Aquatic Ruins (Dolphin Path)",
        43: "Underground Facility (Bombs)",
        44: "Uncategorized",
        45: "Solid Ocean",
        46: "Volcanic",
        47: "Cliffside",
        48: "Thaumanova Reactor",
        49: "Aetherblade",
        50: "Captain Mai Trin Boss"
    },
    "de": {
        1: "Urbanes Schlachtfeld-Fraktal",
        2: "Sumpfland-Fraktal (Blütenschmacht)",
        3: "Unterwasserruinen-Fraktal (Tiefen)",
        4: "Nicht kategorisiertes Fraktal",
        5: "Schneeblind-Fraktal",
        6: "Vulkanisches Fraktal",
        7: "Felswand-Fraktal",
        8: "Untergrundeinrichtung-Fraktal (Gewehre)",
        9: "Einrichtung der Feurigen",
        10: "Einrichtung der Feurigen (Boss)",
        11: "Urbanes Schlachtfeld-Fraktal",
        12: "Nicht kategorisiertes Fraktal",
        13: "Felswand-Fraktal",
        14: "Ätherklingen-Zuflucht",
        15: "Thaumanova-Reaktor",
        16: "Schneeblind-Fraktal",
        17: "Untergrundeinrichtung-Fraktal (Bomben)",
        18: "Unterwasserruinen-Fraktal (Delfine)",
        19: "Vulkanisches Fraktal",
        20: "Solider Ozean-Fraktal (Boss)",
        21: "Sumpfland-Fraktal (Moosmann)",
        22: "Felswand-Fraktal",
        23: "Einrichtung der Feurigen",
        24: "Ätherklingen-Zuflucht",
        25: "Boss der Ätherklingen-Zuflucht (Boss)",
        26: "Unterwasserruinen-Fraktal (Delfine)",
        27: "Schneeblind-Fraktal",
        28: "Vulkanisches Fraktal",
        29: "Untergrundeinrichtung-Fraktal (Bomben)",
        30: "Solider Ozean-Fraktal (Boss)",
        31: "Urbanes Schlachtfeld-Fraktal",
        32: "Sumpfland-Fraktal (Blütenschmacht)",
        33: "Felswand-Fraktal",
        34: "Thaumanova-Reaktor",
        35: "Solider Ozean-Fraktal (Boss)",
        36: "Nicht kategorisiertes Fraktal",
        37: "Schneeblind-Fraktal",
        38: "Untergrundeinrichtung-Fraktal (Gewehre)",
        39: "Einrichtung der Feurigen",
        40: "Einrichtung der Feurigen (Boss)",
        41: "Sumpfland-Fraktal (Moosmann)",
        42: "Unterwasserruinen-Fraktal (Delfine)",
        43: "Untergrundeinrichtung-Fraktal (Bomben)",
        44: "Nicht kategorisiertes Fraktal",
        45: "Solider Ozean-Fraktal (Boss)",
        46: "Vulkanisches Fraktal",
        47: "Felswand-Fraktal",
        48: "Thaumanova-Reaktor",
        49: "Ätherklingen-Zuflucht",
        50: "Boss der Ätherklingen-Zuflucht (Boss)"
    },
    "fr": {
        1: "Fractale du champ de bataille urbain",
        2: "Fractale du marais (Carnasse|Moussu si défi activé)",
        3: "Fractale des ruines aquatiques (Chemin sombre)",
        4: "Fractale non classée",
        5: "Fractale d'Aveugleneige",
        6: "Fractale volcanique",
        7: "Fractale du Flanc de falaise",
        8: "Fractale du complexe souterrain (Fusils)",
        9: "Complexe de la Fusion",
        10: "Boss du Complexe de la Fusion",
        11: "Fractale du champ de bataille urbain",
        12: "Fractale non classée",
        13: "Fractale du Flanc de falaise",
        14: "Refuge étherlame",
        15: "Fractale du Réacteur de Thaumanova",
        16: "Fractale d'Aveugleneige",
        17: "Fractale du complexe souterrain (Bombes)",
        18: "Fractale des ruines aquatiques (Dauphin)",
        19: "Fractale volcanique",
        20: "Fractale de l'océan solide",
        21: "Fractale du marais (Moussu)",
        22: "Fractale du Flanc de falaise",
        23: "Complexe de la Fusion",
        24: "Refuge étherlame",
        25: "Boss du Refuge étherlame",
        26: "Fractale des ruines aquatiques (Dauphin)",
        27: "Fractale d'Aveugleneige",
        28: "Fractale volcanique",
        29: "Fractale du complexe souterrain (Bombes)",
        30: "Fractale de l'océan solide",
        31: "Fractale du champ de bataille urbain",
        32: "Fractale du marais (Carnasse)",
        33: "Fractale du Flanc de falaise",
        34: "Fractale du Réacteur de Thaumanova",
        35: "Fractale de l'océan solide",
        36: "Fractale non classée",
        37: "Fractale d'Aveugleneige",
        38: "Fractale du complexe souterrain (Fusils)",
        39: "Complexe de la Fusion",
        40: "Boss du Complexe de la Fusion",
        41: "Fractale du marais (Moussu)",
        42: "Fractale des ruines aquatiques (Dauphin)",
        43: "Fractale du complexe souterrain (Bombes)",
        44: "Fractale non classée",
        45: "Fractale de l'océan solide",
        46: "Fractale volcanique",
        47: "Fractale du Flanc de falaise",
        48: "Fractale du Réacteur de Thaumanova",
        49: "Refuge étherlame",
        50: "Boss du Refuge étherlame"
    },
    "es": {
        1: "Fractal del campo de batalla urbano",
        2: "Fractal del cenagal",
        3: "Fractal de las ruinas acuáticas",
        4: "Fractal sin clasificar",
        5: "Fractal de la ceguera de la nieve",
        6: "Fractal volcánico",
        7: "Fractal del despeñadero",
        8: "Fractal de la instalación subterránea",
        9: "Fractal de la fragua fundida",
        10: "Fractal de los jefes fundidos",
        11: "Fractal del campo de batalla urbano",
        12: "Fractal sin clasificar",
        13: "Fractal del despeñadero",
        14: "Fractal de los filoetéreos",
        15: "Fractal del reactor taumanova",
        16: "Fractal de la ceguera de la nieve",
        17: "Fractal de la instalación subterránea",
        18: "Fractal de las ruinas acuáticas",
        19: "Fractal volcánico",
        20: "Fractal del océano sólido",
        21: "Fractal del cenagal",
        22: "Fractal del despeñadero",
        23: "Fractal de la fragua fundida",
        24: "Fractal de los filoetéreos",
        25: "Fractal de la jefa capitana Mai Trin",
        26: "Fractal de las ruinas acuáticas",
        27: "Fractal de la ceguera de la nieve",
        28: "Fractal volcánico",
        29: "Fractal de la instalación subterránea",
        30: "Fractal del oceano sólido",
        31: "Fractal del campo de batalla urbano",
        32: "Fractal del cenagal",
        33: "Fractal del despeñadero",
        34: "Fractal del reactor taumanova",
        35: "Fractal del océano sólido",
        36: "Fractal sin clasificar",
        37: "Fractal de la ceguera de la nieve",
        38: "Fractal de la instalación subterránea",
        39: "Fractal de la fragua fundida",
        40: "Fractal de los jefes fundidos",
        41: "Fractal del cenagal",
        42: "Fractal de las ruinas acuáticas",
        43: "Fractal de la instalación subterránea",
        44: "Fractal sin clasificar",
        45: "Fractal del océano sólido",
        46: "Fractal volcánico",
        47: "Fractal del despeñadero",
        48: "Fractal del reactor taumanova",
        49: "Fractal de los filoetéreos",
        50: "Fractal de la jefa capitana Mai Trin"
    }
}